### PR TITLE
Add `Row#add_cells` and `Table#add_rows` methods

### PR DESCRIPTION
**Pull request by AlexWayfer**
It allows to add bunches of data in Ruby-core types,
internally converting them to rows and cells.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
Yay! Thank you.

**Comment by AlexWayfer** [comment]
Maybe, release a new version with all changes?

**Comment by westonganger** [comment]
v1.1.0 is now released which contains these changes.

**Comment by AlexWayfer** [comment]
Thank you!

**Pull request merged**
